93 reprocess old bills
clemenshelm/chillbill-recognizer pull request #102
Opened 2016-11-28 14:35 UTC by tamacodechi

Closes #93 
Is this alright? I'm kind of feeling around the dark since I can't really test it. I'd love some input so I can fix it further.

2016-11-28 15:32 UTC, clemenshelm requested changes
In general that's how it should be, comments inline 😄

2016-11-28 15:32 UTC, clemenshelm commented on Rakefile
> +def process(bill_kind, &bill_proc, queue)
Order of attributes is incorrect, `queue` is the second argument.

2016-11-28 15:32 UTC, clemenshelm commented on lib/hub.rb
> +      meteor.subscribe('admin.bills.toReprocess')
Why?

2016-11-28 15:32 UTC, clemenshelm commented on lib/hub.rb
> +        RecognitionWorker.perform_async id, bill[:imageUrl], :queue
Why are you passing the `:queue` symbol?

2016-11-28 15:32 UTC, clemenshelm commented on Rakefile
> +  process(:unprocessed, :unprocessed) do |recognition_result, _bill, meteor|
It's not obvious what the parameters mean. Maybe use named parameters so it's clear what's happening here.

2016-11-28 15:32 UTC, clemenshelm commented on config/sidekiq.yml
> +  - reprocess
Inconsistent naming (particip vs. verb)

2016-12-01 08:51 UTC, tamacodechi commented on lib/hub.rb
> +      meteor.subscribe('admin.bills.toReprocess')
Do I not need to subscribe to the publication of bills to be reprocessed that the web app sends, or are they all under @bills? 🤔

2016-12-01 10:42 UTC, clemenshelm approved these changes

2016-12-01 10:51 UTC, clemenshelm requested changes

2016-12-01 10:51 UTC, clemenshelm commented on lib/hub.rb
> +      meteor.subscribe('admin.bills.toReprocess')
`@bills` is the name of the subscription, so this line is unnecessary.

2016-12-01 10:51 UTC, clemenshelm commented on sidekiq.rb
> +    sidekiq_options queue: queue
Did you check that this works inside of the method? I only saw examples where this was defined on class scope.

2016-12-01 11:25 UTC, tamacodechi commented on sidekiq.rb
> +    sidekiq_options queue: queue
I also thought this but I can't see another way to get the queue value to be able to set the option

2016-12-01 13:01 UTC, clemenshelm commented on sidekiq.rb
> +    sidekiq_options queue: queue
Ok, but did you check that it works? I don't want the recognition to stop working because of this line 😉

2016-12-06 12:02 UTC, clemenshelm commented on sidekiq.rb
> +    sidekiq_options queue: queue
Look what I found :)
http://www.rubydoc.info/gems/sidekiq/Sidekiq/Client#enqueue_to-class_method

2016-12-07 08:40 UTC, tamacodechi commented on sidekiq.rb
> +    sidekiq_options queue: queue
Awesome! So I can use something like 
```        
Sidekiq::Client.enqueue_to(
  :queue, RecognitionWorker, id, bill[:imageUrl]
)
```
. Since I need to do this before we call the worker and for each bill that is pulled from the subscription, would I do this in the rake task? (in which case I can pass the queue directly by name instead of in a variable)

2016-12-07 11:38 UTC, clemenshelm requested changes
Just 1 tiny detail :)

2016-12-07 11:38 UTC, clemenshelm commented on Rakefile
> +  data["versionNumber"] += 1
I think this shouldn't be here, right?

2016-12-07 14:27 UTC, clemenshelm approved these changes

2016-12-07 14:27 UTC, merged