71 no currency detected
clemenshelm/chillbill-recognizer pull request #105
Opened 2016-12-01 10:23 UTC by tamacodechi

Closes #71 
Didn't really create test data because it was something in how the recognizer works and that would mean creating more acceptance tests. It works on the bill that brought up the problem and our original acceptance test :v:

2016-12-01 10:39 UTC, clemenshelm requested changes

2016-12-01 10:39 UTC, clemenshelm commented on lib/bill_recognizer.rb
> +    ]
That's not good. Why not make it an empty array and insert an element in the `unless` block?

2016-12-07 10:05 UTC, tamacodechi commented on lib/bill_recognizer.rb
> +
This blank line is a problem isn't it? 😆

2016-12-07 10:22 UTC, clemenshelm approved these changes

2016-12-07 10:22 UTC, merged