101 relative date detection
clemenshelm/chillbill-recognizer pull request #120
Opened 2016-12-13 10:28 UTC by tamacodechi

Yay 🎉  I'm pretty happy with this one. It looks like it will be relatively simple to build upon! 

I'm a little unsure about a couple of things, that I hope it's okay to get some confirmation on:

**lib/bill_recognizer.rb**
- [x]  Line 164 : Should this have the if invoice_date confirmation as well...? Or rather, should I somehow makes this all a little more robust, because if there is no invoice date it will pass nothing to the due date calculation, as I understand it?
- [x] Would it be a good idea to/can I add ``` if DueDateLabelTerm.any?``` to the end of ```due_datetime = DateCalculation.new(date_words).due_date(invoice_date)```

**lib/calculations/date_calculation.rb**
- [x] Should there be a case for the conditional where there is neither a date nor a relative date after the due date label and therefore it just returns nil? 

Closes #101 and closes #77

2016-12-13 11:37 UTC, clemenshelm commented
Regarding point 2: At the moment not since there's no "real-life" test backing it up.

2016-12-13 11:37 UTC, clemenshelm commented
Same goes for point 3.

2016-12-13 11:38 UTC, clemenshelm requested changes

2016-12-13 11:38 UTC, clemenshelm commented on lib/bill_recognizer.rb
> +    due_datetime = DateCalculation.new(date_words).due_date(invoice_date)
In fact, you don't need to pass the `invoice_date` here, you can just call the `invoice_date` method inside the `DateCalculation`. You also don't need to make a new `DateCalculation` instance here since it's already instantiated at line 146.

2016-12-13 11:51 UTC, tamacodechi commented on lib/bill_recognizer.rb
> +    due_datetime = DateCalculation.new(date_words).due_date(invoice_date)
Hmm. That's true about making the new ```DateCalculation```, but about ```invoice_date``` wouldn't that mean I'm calculating the invoice date from the ```due_method``` and then not returning it?

2016-12-14 09:51 UTC, clemenshelm requested changes
Very nice! Just one tiny detail 😄

2016-12-14 09:51 UTC, clemenshelm commented on lib/detectors/relative_date_detector.rb
> +    private
`private` within a method doesn't make sense. I know that this is part of almost all Detectors, but that doesn’t make it more correct :)

2016-12-14 09:53 UTC, tamacodechi commented on lib/detectors/relative_date_detector.rb
> +    private
Hmm, I think this may have been a Rubocop autocorrect. Should I change it on all the detectors?

2016-12-14 09:56 UTC, clemenshelm commented on lib/detectors/relative_date_detector.rb
> +    private
Yes, please. Just remove it everywhere.

2016-12-14 10:00 UTC, clemenshelm commented on lib/detectors/relative_date_detector.rb
> +    private
Oh, and please resolve the conflicts with master. Thank you 😄

2016-12-14 10:04 UTC, tamacodechi commented on lib/detectors/relative_date_detector.rb
> +    private
Sounds good, but I should still make all those methods private, right? Not just remove t hat keyword ;)

2016-12-14 10:11 UTC, clemenshelm commented on lib/detectors/relative_date_detector.rb
> +    private
Would be nice, but the `private` keyword doesn't work for class methods. Here are some suggestions on that: http://stackoverflow.com/questions/4952980/creating-private-class-method

2016-12-14 12:16 UTC, clemenshelm approved these changes

2016-12-14 12:16 UTC, merged