solved date-of-breach problem
clemenshelm/chillbill-recognizer pull request #131
Opened 2016-12-16 10:55 UTC by Tr4in

Closes #87

2016-12-16 10:57 UTC, clemenshelm approved these changes

2016-12-16 10:58 UTC, clemenshelm commented
Super!

2016-12-16 10:58 UTC, clemenshelm commented
Bitte noch die Konflikte mit dem Master beheben.

2016-12-16 13:37 UTC, clemenshelm commented
Alex, die Konflikte hast aber nicht behoben. Im Endeffekt ist jetzt das File inklusive Konflikten committet. Bitte da sorgfältiger vorgehen!

2016-12-16 16:08 UTC, Tr4in commented
Noch nicht mergen! Es gibt noch Fehler

2016-12-16 16:44 UTC, Tr4in commented
Fehler behoben :+1:

2016-12-20 09:41 UTC, clemenshelm requested changes

2016-12-20 09:41 UTC, clemenshelm commented on spec/models/date_term_spec.rb
> +    term = DateTerm.new(text: '23. Oktober 2015')
Wieso hast du das geändert?

2016-12-20 09:41 UTC, clemenshelm commented on spec/detectors/date_detector_spec.rb
> +    create_following_words(%w(03. Oktober 2016))
Streng genommen müsste das `3. Oktober 2016` sein, nicht `03.`, oder? Zumindest war's im vorigen Test so.

2016-12-20 09:41 UTC, clemenshelm commented
Bitte noch das Rubocop-Problem beheben.

2016-12-28 17:34 UTC, clemenshelm approved these changes

2016-12-28 17:34 UTC, merged