Fix invalid date exception in various cases.
clemenshelm/chillbill-recognizer pull request #138
Opened 2016-12-23 14:35 UTC by clemenshelm

Closes #128 

@Althaire please put detections into the detector, not into the calculator 😉 Thanks!

2016-12-28 10:17 UTC, tamacodechi reviewed
Looks good all around 🙋  Just a couple of questions!

2016-12-28 10:17 UTC, tamacodechi commented on lib/detectors/date_detector.rb
> +  FULL_ENGLISH_DATE_REGEX = /(\d{2} (?:March|May|October) \d{4})/
I didn't touch the regexes with +s because I assumed that this meant they could have 1 or 2 digits for the day and 2 or 4 digits for the year. Would it be wiser to change it to accept 1 or 2 for the day and 2 or 4 for the year? ...Since it was built with + originally, presumably for a reason  😆

2016-12-28 10:17 UTC, tamacodechi commented on lib/detectors/billing_period_detector.rb
> +    if BillingStartLabelTerm.any? && BillingEndLabelTerm.any?
Hmmm... I had a bit of trouble wrapping my head around it, but we should "put detections in the detectors" because we are assigning words to "to" and "from" in the original detector but in the extension (with the BP labels) I had assignments to "to" and "from" in the calculation?

I understand that they are essentially the same because both are searching through recognized words for billing periods' "to" and "from" but I feel like the original detector runs though all the recognized words in the document and filters out the BPs, whereas this extension with the labels runs through already detected words and calculates out the BP "to" and "from". So it detecting the BP or calculating it? And should the calculator only apply the end logic (ie. the method that puts the variable's content in the format we want)?

Just want to clear it up so I build correctly in the future and wrap my head around the core concepts of the recognizer correctly 😅

2016-12-28 10:17 UTC, tamacodechi commented on lib/bill_recognizer.rb
> +         .improve_level
I couldn't find this in the docs 😅  What does this do? Is it like an auto correction of the level channels?

2016-12-28 10:17 UTC, tamacodechi commented on lib/detectors/billing_period_detector.rb
> +    end
Should we have this section before the the one that filters from hyphen and bis? This is a much more accurate recognition since it relies on explicit labels that only apply to the BP, and the hyphen/bis filter could pick up something erroneous first and apply that as the first BP, even when there are labels on the document.

2016-12-28 16:29 UTC, tamacodechi requested changes
Please run ```rubocop --auto-gen-config```
Rubocop doesn't like the recognizer length is different than the one described on the todo file 😅

2016-12-28 17:47 UTC, clemenshelm commented on lib/detectors/date_detector.rb
> +  FULL_ENGLISH_DATE_REGEX = /(\d{2} (?:March|May|October) \d{4})/
I would leave it for now. Everything else would be an assumption which is not backed with test data yet. But yes, probably that's how it's gonna turn out in the end. I just like to see it fail beforehand so we've got data for a new test.

2016-12-28 17:56 UTC, clemenshelm commented on lib/detectors/billing_period_detector.rb
> +    if BillingStartLabelTerm.any? && BillingEndLabelTerm.any?
It's a special case here because the detector is actually a higher-level detector which builds on data already detected by another detector.

For me what differentiates a detector from a calculation is:

- The detector creates terms from already existing data. Each term has a detector, so the `BillingPeriodDetector` creates `BillingPeriodTerm`s and so on.
- The calculation chooses from the underlying terms the appropriate one. So the `BillingPeriodCalculation` would choose the right `BillingPeriodTerm` to be used as the billing period of the invoice.

A strong indicator that what you were doing was actually a detection was that the spec for the calculation said `it "detects …`.

2016-12-28 17:59 UTC, clemenshelm commented on lib/detectors/billing_period_detector.rb
> +    end
I think it doesn't matter, both sections can insert `BillingPeriodTerm`s. So no matter in what order you execute them, by the end of the method you'll return a dataset which contains results from both sections. Figuring out the right `BillingPeriodTerm` is subject to the calculation.

2016-12-28 18:18 UTC, clemenshelm commented on lib/bill_recognizer.rb
> +         .improve_level
It's a method on the `ImageProcessor`. It uses the RMagick `level` method: https://rmagick.github.io/image2.html#level

This basically increases the contrast on the bill.

2016-12-30 09:10 UTC, tamacodechi commented on lib/detectors/billing_period_detector.rb
> +    if BillingStartLabelTerm.any? && BillingEndLabelTerm.any?
Perfect, thank you for clearing that up! 👍

2016-12-30 09:18 UTC, tamacodechi commented on lib/detectors/billing_period_detector.rb
> +    end
That makes sense, the system should be smart enough to calculate the correct BP regardless of the order in which they are collected 🙌

2016-12-30 09:20 UTC, tamacodechi approved these changes

2017-01-02 10:54 UTC, merged