Report error when PDF cannot be read.
clemenshelm/chillbill-recognizer pull request #139
Opened 2016-12-23 17:40 UTC by clemenshelm

Closes #137

2016-12-28 09:22 UTC, tamacodechi reviewed
Awesome 😉  This isn't the case when the recognizer gives out that big block of text when leading a PDF, is it? (I ask because those still spit out recognized words, so I'm wondering if I've ever encountered an unsupported PDF)

2016-12-28 09:22 UTC, tamacodechi commented on spec/bill_recognizer_spec.rb
> +    # This spec will fail once Ghostscript supports this crappy PDF. Awesome!
Great comment, because now when it does fail we will know why without having to dig around 👍

2016-12-28 09:22 UTC, tamacodechi commented on lib/image_processor.rb
> +      raise InvalidImage, 'Cannot read image.' unless original_image
Should the error be more descriptive? If this is in the case of PDF only then maybe something like "Cannot read image. Unsupported PDF." might be a little more descriptive 😀

2016-12-28 16:31 UTC, tamacodechi requested changes
The new test in ```spec/bill_recognizer_spec.rb``` doesn't pass 🙈

2016-12-30 07:58 UTC, clemenshelm commented on lib/image_processor.rb
> +      raise InvalidImage, 'Cannot read image.' unless original_image
It might be more descriptive, but it also might be wrong. If there is no image, it doesn't necessarily mean there's an error with the PDF. It could also be a JPG or a PNG in an invalid format. So I'd rather go with being more generic than with being more specific, but wrong 😉

2016-12-30 08:00 UTC, clemenshelm commented
No, the big block of text are probably just warnings. If the PDF is invalid, it won't be able to recognize anything because there won't be an image.

2016-12-30 08:34 UTC, tamacodechi commented on lib/image_processor.rb
> +      raise InvalidImage, 'Cannot read image.' unless original_image
Ahh makes sense, I meant it more as an example where we extract the extension. So we can't really pass the file extension because it might simply be in the incorrect format? Then again the words "unsupported" kind of indicate that it is an unsupported file of that extension, and in the case of pngs and jpgs we know that it is that they're in an invalid format?

2016-12-30 09:09 UTC, tamacodechi commented
Yeah that I got I meant more that the spec isn't getting what it expected on Codeship. Odd, I fetched your branch and it all passed on my machine, so I would chalk it up to the environment on Codeship, right?

2017-01-02 13:12 UTC, clemenshelm commented
Just to clarify why there are so many commits and strange new files: I changed Codeship to use Docker to give us full control over the library versions we use (because there was a different version of Ghostscript used which made the test fail).

2017-01-03 09:27 UTC, tamacodechi approved these changes
I'd love to pick your brain on some of the changes but seeing as merging this is kinda urgent I'll approve first and ask questions later, because I don't see any changes that need to be made 👍

2017-01-03 09:42 UTC, merged

2017-01-03 09:43 UTC, clemenshelm commented
Ok, I merged it 😄 

Feel free to comment and I'll answer! 😉