Make Unprocessable File Error pass recognizer version
clemenshelm/chillbill-recognizer pull request #141
Opened 2016-12-28 15:00 UTC by tamacodechi

Closes #140

~NOT READY YET.~ Okay it's ready now 😆

2016-12-30 07:54 UTC, clemenshelm requested changes

2016-12-30 07:54 UTC, clemenshelm commented on spec/bill_recognizer_spec.rb
> +    ).to eq 'Unprocessable file type: .p7s. Recognizer version: 13'
This is not how it should be. Instead, there should be an attribute `recognizerVersion`in the result, just like a normal result.

2016-12-30 08:28 UTC, tamacodechi commented on spec/bill_recognizer_spec.rb
> +    ).to eq 'Unprocessable file type: .p7s. Recognizer version: 13'
Ahh makes sense! Thankfully should be an easy fix, so I'll get right on that 😉

2017-01-03 14:04 UTC, clemenshelm approved these changes

2017-01-03 14:04 UTC, clemenshelm commented
Yeees! Very nice now!

2017-01-03 14:04 UTC, merged