Refactor to pass Rubocop standards
clemenshelm/chillbill-recognizer pull request #142
Opened 2017-01-03 15:44 UTC by tamacodechi

2 errors down, 49 to go! 😅 
With this PR there are no more troubles caused by the ```spec/spec_cache.rb``` file

Is this a good way to do it? I don't know if there are issues against passing around too many arguments from method to method.

2017-01-03 20:24 UTC, clemenshelm requested changes

2017-01-03 20:24 UTC, clemenshelm commented on spec/spec_cache.rb
> +    image_path = get_image_path(bucket, region, file_basename)
The method name implies that the method just gets the image path when in fact it downloads and stores a file from S3.

I'd rather refactor it to something like

```ruby
image_path = cache_file(file_basename.to_s) do |path|
  download_from_s3(to: path)
end
```

2017-01-03 20:24 UTC, clemenshelm commented on spec/spec_cache.rb
> +    image_path = get_image_path(bucket, region, file_basename)
Btw, why do we need to call `file_basename.to_s`? What type is `file_basename`?

2017-01-17 09:59 UTC, tamacodechi commented
I have no idea why but I have two branches doing very similar things for this solution. I'm going to close this PR and open a new one with the more correct solution. (This is what I hate about being away for so long, I had actually discovered this mess before I got sick 😞 )

2017-01-17 09:59 UTC, closed without merging