36 spec cache refactor
clemenshelm/chillbill-recognizer pull request #149
Opened 2017-01-17 10:08 UTC by tamacodechi

Re-did the PR for the spec cache retriever refactor. For the first time in my life, I worked on/did the PR from the wrong branch ._. Completely bizarre.

Closes #36

2017-01-17 15:24 UTC, clemenshelm requested changes

2017-01-17 15:24 UTC, clemenshelm commented on spec/spec_cache.rb
> +  def create_tempfile(image_path, file_extension)
There's a bit more happening here than creating a tempfile: The downloaded file is copied to a tempfile. How about `store_in_tempfile` or `copy_to_tempfile`?

2017-01-24 19:24 UTC, merged

2017-01-24 19:25 UTC, clemenshelm commented
Me gusta. Mucho. 👌

2017-01-25 08:55 UTC, tamacodechi commented
🎉
But hey! You're supposed to be on holiday, aren't you? 😉