38 refactor bill image retriever
clemenshelm/chillbill-recognizer pull request #150
Opened 2017-01-17 10:57 UTC by tamacodechi

It may seem a bit silly to compartmentalize some of the things that are just a couple of lines, but if this method ever needs to do more it now has a couple of extra lines allowed to do so :)

I'm not 100% sure about about making image_file an instance variable but it's the only way without having to pass it around to every method, is this an okay way to do it? 

Closes #38

2017-01-17 15:17 UTC, clemenshelm commented
I'd rather do the following things:

- Deconstruct the URL in the constructor (also the file extension thing) and save the results as instance variables.
- Move the `Tempfile` part into your `get_bill_from_s3` method which should return the file
- Maybe then you don't even need the `determine_extension_validity` method anymore.

2017-01-17 15:20 UTC, clemenshelm commented
Why? Because the deconstructed URL is just another (more relevant) representation of the URL, so we won't need to store the URL in an instance variable anymore but only the relevant parts. This is also no heavy lifting, which I wouldn't put into a constructor (like downloading a file).

2017-01-19 13:50 UTC, clemenshelm requested changes

2017-01-19 13:50 UTC, clemenshelm commented on lib/bill_image_retriever.rb
> +    determine_extension_validity
One thought here: I don't find it intuitive that `determine_extension_validity` returns the `image_file`. I think this method would read much more clearly something like this:

```ruby
def save
  ensure_extension_validity
  download_bill_from_s3
end
```
I’d do the extension check first because it's pointless to download the file when the extension is invalid.

2017-01-19 13:52 UTC, tamacodechi commented on lib/bill_image_retriever.rb
> +    determine_extension_validity
That makes loads of sense! 😅

2017-01-19 14:09 UTC, tamacodechi commented on lib/bill_image_retriever.rb
> +    determine_extension_validity
Hmm is it okay for ```download_bill_from_s3``` to return ```@image_file```? We need @image_file to be returned somewhere.

2017-01-19 14:59 UTC, clemenshelm commented on lib/bill_image_retriever.rb
> +    determine_extension_validity
I think yes, because to me it seams intuitive that `download_bill_from_s3` returns a file which has been downloaded. We probably won't need the `@image_file` instance variable anymore because it's only used within this method then.

2017-01-28 09:32 UTC, clemenshelm requested changes

2017-01-28 09:32 UTC, clemenshelm commented on lib/bill_image_retriever.rb
> +    case @file_extension
This is a little bloated now. In fact it's enough to write

```ruby
# put this somewhere at the top of the class
VALID_EXTENSIONS = ['.pdf', '.png', '.jpg', '.jpeg'].freeze

def determine_extension_validity
  unless VALID_EXTENSIONS.include?(@file_extension)
    raise UnprocessableFileError, @file_extension
  end
end
```

2017-02-01 09:49 UTC, tamacodechi commented on lib/bill_image_retriever.rb
> +    case @file_extension
True, since we only have two cases and one of them only returns, this makes **so much more** sense 🎉  I'm a bit mad at myself for not catching that 😅

2017-02-01 12:23 UTC, clemenshelm commented
Is this ready for review now? Please let me know by tagging it with `needs_review` 😉

2017-02-01 12:24 UTC, tamacodechi commented
Ahh yes! Sorry I was waiting for the build to finish before that (I wasn't going to tag it if it was broken) and it took so long I just moved onto something else and forgot 😅

2017-02-01 12:26 UTC, clemenshelm commented
Oh, I see. There's a merge conflict now that I merged the other branch. Could you resolve it?

2017-02-01 15:34 UTC, clemenshelm approved these changes

2017-02-01 15:35 UTC, clemenshelm commented
Merge conflicts again 🦀

2017-02-02 14:06 UTC, merged