Date detector refactor
clemenshelm/chillbill-recognizer pull request #155
Opened 2017-01-26 09:33 UTC by tamacodechi

I imagine this will be the case with most detectors, but the find_x method is always way too long 😣 
I've made this PR for now, but I'd love some opinions on it before proceeding with it.

2017-01-26 09:44 UTC, tamacodechi commented on lib/detectors/date_detector.rb
> +  end
I understand why we remove the short period dates first, because otherwise period dates would get detected as either/or long period dates, but why are hungarian dates also part of the words we reduce from ```Word.all```? Do they also interfere with the long period dates?

If so would something like ```find_and_reduce_interfering_period_dates``` be a better name for this method?

2017-01-26 09:44 UTC, tamacodechi commented on lib/detectors/date_detector.rb
>        end
Does anyone else see a way to cut this block down? It's pretty much the same in most detectors and it would be great to cut this down. The fixes I can come up with are kind of fixes for the sake of fixes instead of it actually being better... I feel like moving most things out would defeat the purpose of the original ```find_x``` method

2017-01-28 09:45 UTC, clemenshelm requested changes

2017-01-28 09:45 UTC, clemenshelm commented on lib/detectors/date_detector.rb
> +  end
I think the year of the hungarian date could be considered in another date accidentally. But the easiest way to find out is to remove the `hungarian_dates` from the `reduced_words` and run the tests. If they still pass, there's no reason for the hungarian dates to be removed. 😉

2017-01-28 09:45 UTC, clemenshelm commented on lib/detectors/date_detector.rb
> +  def self.find_long_dates_with_periods(words)
Why *long* dates if the regex says `SHORT_PERIOD_DATE_REGEX`?

2017-01-28 09:45 UTC, clemenshelm commented on lib/detectors/date_detector.rb
>        end
I think it belongs into a `Detector` superclass.

2017-01-28 09:45 UTC, clemenshelm commented on lib/detectors/date_detector.rb
> +        term = create_new_term(regex, after_each_word, max_words)
`create` is not a good term in this context as it implies that the term gets created in the database. Rather use `initialize`.

2017-02-01 16:14 UTC, tamacodechi commented on lib/detectors/date_detector.rb
> +        term = create_new_term(regex, after_each_word, max_words)
Very true! I didn't think of it that way! 😅  I will try to keep that kind of context in mind for the future, thanks for the tip! 💃

2017-02-02 12:29 UTC, clemenshelm approved these changes

2017-02-02 12:30 UTC, merged