44 refactor price calculation
clemenshelm/chillbill-recognizer pull request #156
Opened 2017-01-26 13:56 UTC by tamacodechi

Closes #44 and closes #40 

Pleases Rubocop and is hopefully more legible 🐑

2017-01-26 14:37 UTC, mina1604 reviewed
looks good :)

2017-01-28 09:14 UTC, clemenshelm requested changes

2017-01-28 09:14 UTC, clemenshelm commented on lib/calculations/price_calculation.rb
> +    @remaining_prices.select do |price|
Please don't use instance variables to pass state in the context of a single method call. They are meant for longer-lasting information across several method calls (like `@net_amount` and `@vat_amount`).

Instead, pass `remaining_prices` as an argument.

2017-02-01 13:52 UTC, tamacodechi commented on lib/calculations/price_calculation.rb
> +    @remaining_prices.select do |price|
Gotcha 😉  Sorry for all this instance variable mess, will read up more in my free time to make sure I get a better idea of when to use them. It seemed wrong to have to pass ``` remaining_prices ``` down two layers 😅

2017-02-01 15:29 UTC, clemenshelm commented on lib/calculations/price_calculation.rb
> +    @remaining_prices.select do |price|
It's not wrong what you did and probably many programmers will use them like you do. My experience is just to avoid state wherever possible. And instance variables always create state because they live as long as the object does. This can lead to tricky problems which you can easily avoid by not using them unless there's a good reason to 😄

2017-02-01 15:29 UTC, clemenshelm approved these changes

2017-02-01 15:29 UTC, merged