48 rewrite price spec test
clemenshelm/chillbill-recognizer pull request #165
Opened 2017-01-27 10:25 UTC by tamacodechi

Closes #48

2017-01-28 09:08 UTC, clemenshelm requested changes

2017-01-28 09:08 UTC, clemenshelm commented on spec/detectors/price_detector_spec.rb
> +    )
How is this an improvement? Isn't the easiest fix for the `PercentStringArray` rule just to rewrite the method call to `create_following_words(['54,', '00'])`?

2017-02-01 13:49 UTC, tamacodechi commented on spec/detectors/price_detector_spec.rb
> +    )
Ahh right this works! I just thought it would be good to have the actual data that came from a test but I've changed it to this leaner format. 

Rubocop autocorrect just breaks the test because it keeps the same format but removes the comma, so no really testing what we want which was the two words, one of which has a comma 🤖 💦

2017-02-01 15:33 UTC, clemenshelm approved these changes

2017-02-01 15:34 UTC, clemenshelm commented
Awesome! The merge conflicts in `.rubocop_todo.yml` are a pain in the pass 😉

2017-02-02 14:17 UTC, merged