148 correct bill orientation
clemenshelm/chillbill-recognizer pull request #178
Opened 2017-02-08 09:00 UTC by tamacodechi

Closes #148 
Questions on the comments :)
Hope this does the trick 🎉

2017-02-08 09:16 UTC, tamacodechi commented on lib/bill_recognizer.rb
> +    @orientation = image.get_orientation
Again with the instance variables 😅  Does it make more sense in the case? We can only really ```get_orientation``` if we have ```image``` for which we need to be in this method or call everything all over again in it's own method.

2017-02-08 09:16 UTC, tamacodechi commented on lib/image_processor.rb
> +    orientation.first.last
This ```.first.last``` is because ```get_exif_by_entry``` returns an array with an array, in this case: ```[["Orientation", "6"]]``` It's a bit weird but it does the job. I tried looking around but I didn't find any other kind of accessor, is it clear or should I leave a comment in the code in case anyone can't fathom why we do ```.first.last``` ? 🤔

2017-02-08 12:06 UTC, tamacodechi commented on lib/bill_recognizer.rb
> +    @orientation = image.calculate_orientation
Again with the instance variables 😅 Does it make more sense in the case? We can only really get_orientation if we have image for which we need to be in this method or call everything all over again in it's own method.

2017-02-09 14:00 UTC, tamacodechi commented on lib/bill_recognizer.rb
> +    @orientation = image.calculate_orientation
Again with the instance variables 😅 Does it make more sense in the case? We can only really get_orientation if we have image for which we need to be in this method or call everything all over again in it's own method.

2017-02-09 14:04 UTC, tamacodechi commented
It is now ready for review 👍

2017-02-09 15:11 UTC, clemenshelm requested changes

2017-02-09 15:11 UTC, clemenshelm commented on lib/bill_recognizer.rb
> +    @orientation = image.calculate_orientation
It's ok, but I think you could improve the naming. Here you're talking about orientation, but at the bottom you're talking about `clockwiseRotationsRequired` all of a sudden 😉 

Maybe you could rename the variable and the method to also reflect that it's about rotations?

2017-02-09 15:11 UTC, clemenshelm commented on lib/image_processor.rb
> +  attr_reader :image_height
Better: `attr_reader :image_width, :image_height`

2017-02-09 15:11 UTC, clemenshelm commented on lib/image_processor.rb
> +    end
I'm not sure if Rubocop will like it, but it's possible to write simple case statements more concise:

```ruby
case orientation.first.last
when '6' then 1
when '3' then 2
when '8' then 3
else 0
end
```

2017-02-09 15:11 UTC, clemenshelm commented on spec/image_processor_spec.rb
> +      "https://chillbill-prod.s3-eu-central-1.amazonaws.com/#{file_id}.JPG"
Instead of downloading images here, you could just create test images with RMagick: https://rmagick.github.io/image1.html#new (and save them)
Setting the EXIF data should also work: http://stackoverflow.com/questions/20901713/how-to-write-custom-metadata-to-an-image-created-by-rmagick

Then you don't have a dependency on the bill being there and on the internet connection. Plus you specify the dimensions explicitly which makes the test more understandable.

2017-02-09 15:14 UTC, tamacodechi commented on spec/image_processor_spec.rb
> +      "https://chillbill-prod.s3-eu-central-1.amazonaws.com/#{file_id}.JPG"
Ahh great idea! Yes, I hated that this partially depended on the retriever which is besides the point of these tests! Thank you, this is great 👏

2017-02-09 15:14 UTC, tamacodechi commented on lib/image_processor.rb
> +    end
Rubocop didn't mind but I do prefer this myself too, so I will change it ;)

2017-02-09 15:14 UTC, tamacodechi commented on lib/image_processor.rb
> +  attr_reader :image_height
Will do 👍

2017-02-09 15:16 UTC, tamacodechi commented on lib/bill_recognizer.rb
> +    @orientation = image.calculate_orientation
Perfect! I wasn't sure if it was necessary. I also prefer it because it's more consistent but also then the variable name would be quite long and I didn't know if it was just my being nitpicky 😅

2017-02-10 14:28 UTC, clemenshelm commented
@Althaire I didn't figure out how to write the EXIF-Tag, probably it's not even possible with RMagick (the PNG stuff might have been other metadata because PNGs don't even support EXIF from what I've read).

Instead I created a 2x3 test image file with this tag and it works fine 😄

2017-02-10 14:33 UTC, clemenshelm approved these changes

2017-02-10 14:44 UTC, merged