198 invoice number recognition
clemenshelm/chillbill-recognizer pull request #209
Opened 2017-03-29 12:08 UTC by tamacodechi

closes #198

2017-04-04 08:26 UTC, clemenshelm requested changes
🍰

2017-04-04 08:26 UTC, clemenshelm commented on lib/calculations/invoice_number_calculation.rb
> +        InvoiceNumberTerm.right_below(InvoiceNumberLabelTerm.first)
better:

```ruby
label = InvoiceNumberLabelTerm.first
if label
  invoice_number = InvoiceNumberTerm.right_after(label) || InvoiceNumberTerm.right_below(label)
…
```

2017-04-04 08:26 UTC, clemenshelm commented on lib/calculations/invoice_number_calculation.rb
> +      invoice_number = InvoiceNumberTerm.where(needs_label: true).first
I don't understand this. Why do you query for an `InvoiceNumberTerm` which needs a label when there is no label?

2017-04-04 08:26 UTC, clemenshelm commented on lib/detectors/invoice_number_label_detector.rb
> +    /(Invoice number:|Billing ID|Rechnung Nr.:)/
Oh, this is where you meant that it's kind of a random partition of the Regex 😄 

What I'm wondering: Since all of these Regexes are just whole strings, couldn't we just make one large array of strings up there and then merge them into one Regex? We do something similar already in the `CurrencyDetector`.

2017-04-04 08:26 UTC, clemenshelm commented on lib/models/dimensionable.rb
> +          (following.left - current.right) < (following.height * 32) &&
Could we solve this differently here? I think we talked about the problem that `height` is relative to the page height and therefore not really suitable for representing a space (because width and height are independent from each other). I think the best solution would be to define a "letter width" as `current.width / current.text.size` (or something like that) and then use a multiple of that as the threshold.

2017-04-04 08:26 UTC, clemenshelm commented on lib/models/word.rb
> +    max_space_width = previous_word.height * 1.76
Here it would also be nice to actually use the letter width mentioned above.

2017-04-04 08:26 UTC, clemenshelm commented on spec/calculations/invoice_number_calculation_spec.rb
> +    expect(invoice_number.invoice_number).to be_nil
Bad naming (`invoice_number.invoice_number`)

2017-04-04 11:29 UTC, tamacodechi commented on lib/models/dimensionable.rb
> +          (following.left - current.right) < (following.height * 32) &&
I did built this but the multiplier was also very large because there are some cases where it's the word right after but the information is in columns eg.

| Invoice number: | 23123123123123123123123 |
|:---|---:|
| Invoice date:   |                 12.3.45 |

So I felt it didn't make sense to build this fix when it's not really fixing our problem. Should I go ahead and implement it anyway?

2017-04-10 09:52 UTC, clemenshelm commented
I updated the credentials on master. If you merge master into this branch, it should work.

2017-04-10 11:53 UTC, clemenshelm requested changes

2017-04-10 11:53 UTC, clemenshelm commented on lib/calculations/invoice_number_calculation.rb
> +      invoice_number = InvoiceNumberTerm.where(needs_label: nil).first
`needs_label: nil` doesn't make much sense semantically. How about `needs_label: false`?

2017-04-11 14:46 UTC, clemenshelm approved these changes

2017-04-11 14:46 UTC, merged