Feature/billing period detector
clemenshelm/chillbill-recognizer pull request #21
Opened 2016-09-20 14:38 UTC by tamacodechi

Finally, a PR for this feature 👏 
Thank you for all the help! 😁 
Hope I didn't miss any indentations!

_Edit: This will probably take a bit long, I was about 30% done when I ran all the tests and there were 40 failing tests. I think it would be better to run the tests after each of the fixes to make sure everything stays intact._

**Fixes:**
- [x] **spec/acceptance/bill_recognition_spec.rb** - date period iso 
- [x] **lib/detectors/billing_period_detector.rb** - require_relative
- [x] **lib/detectors/billing_period_detector.rb** - setting text
- [x] **lib/boot.rb** - foreign keys
- [x] **lib/calculations/billing_period_calculation.rb** - require_relative
- [x] **lib/calculations/date_calculation.rb** - require_relative
- [x] **lib/bill_recognizer.rb** - invoice billing period
- [x] **lib/detectors/billing_period_detector.rb** - from > to
- [x] **lib/models/dimensionable.rb** - following.height
- [x] **spec/detectors/billing_period_detector_spec.rb** - unclear describe
- [x] **spec/models/dimensionable_spec.rb** - describe dimensionable

Closes #71

2016-09-21 08:58 UTC, clemenshelm requested changes
Good job! Just a few little questions and fixes 😉

2016-09-21 08:58 UTC, clemenshelm commented on lib/bill_recognizer.rb
> +    ).invoice_billing_period
I don't see the value of naming it `invoice_billing_period`. We're only in the context of an invoice here, so it seems a little redundant to me. 😉

2016-09-21 08:58 UTC, clemenshelm commented on lib/boot.rb
> +  Integer :to_id
Could you use `foreign_key` here as described in http://sequel.jeremyevans.net/rdoc/files/doc/association_basics_rdoc.html? Advantage: Explicit reference to the primary key of another table.

2016-09-21 08:58 UTC, clemenshelm commented on lib/calculations/billing_period_calculation.rb
> +require_relative '../models/word'
Why do we need the `require_relative`s here? Seems like these classes don't get referenced in the file. If it's for the specs, please move the `require_relative`s to the spec file.

2016-09-21 08:58 UTC, clemenshelm commented on lib/calculations/date_calculation.rb
> +require_relative '../boot'
Why do we need this `require_relative` here, but not on the `BillingPeriodCalculation`?

2016-09-21 08:58 UTC, clemenshelm commented on lib/detectors/billing_period_detector.rb
> +require_relative './date_detector'
Are the `require_relative`s above really necessary?

2016-09-21 08:58 UTC, clemenshelm commented on lib/detectors/billing_period_detector.rb
> +      if from && to && from.text < to.text
What does `from.text < to.text` do?

2016-09-21 08:58 UTC, clemenshelm commented on lib/detectors/billing_period_detector.rb
> +          text: from.text + ' - ' + to.text,
Since `from` and `to` are both dependencies of `BillingPeriodTerm`, the assignment of the text should be in the `initialize` method (since you probably want the text to have this format for all `BillingPeriodTerm`s).

Also, the `text` attribute is supposed to represent the original text, so the dates should be separated by the original separator (`"-"` or `"bis"`).

2016-09-21 08:58 UTC, clemenshelm commented on lib/models/dimensionable.rb
> +      all.find {|following| (following.left > current.right) && (following.left - current.right) < (following.height * 1)}
`following.height` instead of `(following.height * 1)` would be enough 😉

2016-09-21 08:58 UTC, clemenshelm commented on spec/acceptance/bill_recognition_spec.rb
> +    expect(bill_attributes[:billingPeriod]).to eq '01.03.2015 - 31.03.2015'
This is inconsistent. `bill_attributes[:invoiceDate]` is formatted as `YYYY-MM-DD` whereas the `bill_attributes[:billingPeriod]` uses `DD.MM.YYYY`. Please also use `YYYY-MM-DD` here.

There is an ISO specification for representing date ranges (https://de.wikipedia.org/wiki/ISO_8601#Zeitspannen), so I recommend that we use it. For this example the format would be `2015-03-01/2015-03-31`.

2016-09-21 08:58 UTC, clemenshelm commented on spec/detectors/billing_period_detector_spec.rb
> +  it "does not recognize an invoice date that is the same as part of the billing period as part of the billing period" do
I don't understand this description.

2016-09-21 08:58 UTC, clemenshelm commented on spec/models/dimensionable_spec.rb
> +describe DateTerm do
Actually it should describe `Dimensionable`.

2016-09-21 09:01 UTC, tamacodechi commented on lib/bill_recognizer.rb
> +    ).invoice_billing_period
Good point! I think I initially did it to keep conformity with invoice date 😅

2016-09-21 09:07 UTC, tamacodechi commented on spec/detectors/billing_period_detector_spec.rb
> +  it "does not recognize an invoice date that is the same as part of the billing period as part of the billing period" do
I can't think of a better way to phrase it... Basically if there is a date that is repeated, eg.:
1.11.2011,
1.11.2011,
-,
20.11.2011.

It will ignore the first one, and still save that as a standalone date. There was an error where this repeating date would be saved as part of a billing period.

2016-09-21 16:06 UTC, clemenshelm commented on spec/detectors/billing_period_detector_spec.rb
> +  it "does not recognize an invoice date that is the same as part of the billing period as part of the billing period" do
Ok. But you aren't testing here that the standalone date isn't part of the billing period, are you? Maybe a description could be something like `"it doesn't consider other dates as part of the billing period"`?

2016-09-22 13:16 UTC, tamacodechi commented on spec/detectors/billing_period_detector_spec.rb
> +  it "does not recognize an invoice date that is the same as part of the billing period as part of the billing period" do
Sounds good, it was more specific to dates that are the same as dates from the billing period, but I think your suggestion for the description is clearer :)

2016-10-11 18:49 UTC, clemenshelm requested changes
Excellent! Just one tiny remark :)

2016-10-11 18:49 UTC, clemenshelm commented on lib/detectors/billing_period_detector.rb
> +    Word.where(text: ['-', 'bis']).all.select do |term|
The purpose of `select` is to create a resulting array with filtered values (see http://ruby-doc.org/core-2.3.1/Enumerable.html#method-i-select).

If you only want to iterate over an array, use `each` instead.

2016-10-12 10:41 UTC, merged