fixed future dates
clemenshelm/chillbill-recognizer pull request #218
Opened 2017-04-11 11:51 UTC by Tr4in

Closes #206

2017-04-11 14:03 UTC, tamacodechi requested changes
Please autogenerate the rubocop todo :) `to_datetime` being one line longer is making rubocop angry 😉

2017-04-11 14:03 UTC, tamacodechi commented on lib/detectors/date_detector.rb
> +    find_multi_word_dates(reduced_words)
Does the test you added need this change to pass? 😅 
If so, please change the name to reflect that. Thanks 👍

2017-04-11 14:13 UTC, tamacodechi commented on spec/detectors/date_detector_spec.rb
> +    )
Can you add a blank line after this parethesis? That way it looks just as nice as all our other tests 😂

2017-04-27 10:06 UTC, tamacodechi requested changes

2017-04-27 10:06 UTC, tamacodechi commented on spec/detectors/date_detector_spec.rb
> +    )
I don't think this should get detected at all 🤔
It's not a date.

2017-04-29 00:13 UTC, Tr4in commented on spec/detectors/date_detector_spec.rb
> +    )
Although it is not a valid date it matches short slash regex

2017-05-03 07:36 UTC, tamacodechi requested changes
Please update the rubocop todo ;)

2017-05-03 07:36 UTC, tamacodechi commented on spec/detectors/date_detector_spec.rb
> +    )
You could limit the regex to accept dates from this decade for now :) I guess this solution won't work for all cases but it'll work for now

2017-05-03 07:38 UTC, clemenshelm commented on spec/detectors/date_detector_spec.rb
> +    )
I'd prefer not to, the decade isn't that long anymore and I'd like to avoid that things stop all of a sudden on Jan 1, 2020 😉

2017-05-03 07:40 UTC, clemenshelm commented on spec/detectors/date_detector_spec.rb
> +    )
The fact that there's `51` and `38` disqualifies it as a date as only one of them can be a year. Please update the regex appropriately.

2017-05-03 07:52 UTC, tamacodechi commented on spec/detectors/date_detector_spec.rb
> +    )
I was thinking that too, and also there might be non dates that fall into this decade, so it's not a very healthy solution 😔

2017-05-10 08:36 UTC, tamacodechi approved these changes

2017-05-10 09:18 UTC, merged