232 first ml model
clemenshelm/chillbill-recognizer pull request #249
Opened 2017-05-09 14:00 UTC by Thomas1e

closes #232

2017-05-09 20:48 UTC, clemenshelm requested changes
Ein paar kleine Änderungen wären nett, hauptsächlich geht's um Übersetzungen. Sonst super, soweit ich's verstehe 😄

2017-05-09 20:48 UTC, clemenshelm commented on docs/machine_learning.md
> +Rscript --vanilla use_model.R 24PC5D5oeL6fb8a5n.csv
Bitte hier noch alles auf Englisch.

2017-05-09 20:48 UTC, clemenshelm commented on lib/machine_learning/generate_model.R
> +# Set Working Directory to Source file loaction (only necessary in RStudio)
loaction => location

2017-05-09 20:48 UTC, clemenshelm commented on lib/machine_learning/generate_model.R
> +# RScript uses automatically the right directionary
directionary => directory ?

2017-05-09 20:48 UTC, clemenshelm commented on lib/machine_learning/generate_model.R
> +s = sample(n, round(n * 0.7))
Was bedeutet `0.7`? Dafür wäre ein Kommentar gut. Heißt es, dass 70% der Datensätze für's Training verwendet werden?

2017-05-09 20:48 UTC, clemenshelm commented on lib/machine_learning/generate_model.R
> +s = sample(n, round(n * 0.7))
Grundsätzlich können auch Variablennamen viel Bedeutung vermitteln, wenn sie länger als ein Buchstabe sind 😉

2017-05-09 20:48 UTC, clemenshelm commented on lib/machine_learning/generate_model.R
> +#print(data_test[data_test$valid_amount[p == 1] == 0,])
Konsistent wär's, hier auch alles auf Englisch zu schreiben.

2017-05-09 20:48 UTC, clemenshelm commented on lib/machine_learning/generate_tuples.R
> +  part2 = price_list[ combinations$Var2, c("price_id",  "text", "price_cents", "left","right","top", "bottom")]
Bezüglich Leerzeichen nach Kommas wäre eine Konvention gut. Ich würde vorschlagen, immer ein Leerzeichen nach Kommas zu machen.

2017-05-09 20:48 UTC, clemenshelm commented on lib/machine_learning/generate_tuples.R
> +  part2 = price_list[ combinations$Var2, c("price_id",  "text", "price_cents", "left","right","top", "bottom")]
Am besten wäre es, einen Linter zu verwenden, der automatisch den Code-Style überprüft. Der hier scheint Standard zu sein: https://github.com/jimhester/lintr

Ich füge das als eigenen Task hinzu.

2017-05-10 08:02 UTC, Thomas1e commented on lib/machine_learning/generate_model.R
> +#print(data_test[data_test$valid_amount[p == 1] == 0,])
Das hab ich noch nicht geändert, weil der Code auch falsch ist. Das muss ich mir nochmal genauer anschauen.

2017-05-10 08:04 UTC, Thomas1e commented on lib/machine_learning/generate_tuples.R
> +  part2 = price_list[ combinations$Var2, c("price_id",  "text", "price_cents", "left","right","top", "bottom")]
Die Leerzeichen nach dem Komma habe ich eh schon versucht einzuhalten, ich war aber anscheinend nicht konsequent genug. Das mit dem Linter ist eine gute Idee.

2017-05-10 08:05 UTC, Thomas1e commented on lib/machine_learning/generate_model.R
> +# RScript uses automatically the right directionary
ja, Tippfehler

2017-05-10 08:05 UTC, Thomas1e commented on lib/machine_learning/generate_model.R
> +# Set Working Directory to Source file loaction (only necessary in RStudio)
ja, Tippfehler

2017-05-10 08:06 UTC, Thomas1e commented on lib/machine_learning/generate_model.R
> +s = sample(n, round(n * 0.7))
mach ich

2017-05-10 09:01 UTC, clemenshelm approved these changes
Supi! 😸

2017-05-10 09:18 UTC, merged