refactored decimal price regex
clemenshelm/chillbill-recognizer pull request #263
Opened 2017-05-23 03:11 UTC by Tr4in

I reduced it a bit. Lesser complex this time. :sun_with_face: 

Closes #256

2017-05-24 10:19 UTC, tamacodechi requested changes
Nice ✌️ Just a couple of things and then we can merge it! 🎉

2017-05-24 10:19 UTC, tamacodechi commented on lib/detectors/price_detector.rb
> +    /(?:^|[^\d,A])(€?([1-9]{1}\d{0,3}|0)(.\d{3})?[,.](\d{2,3}|-))$/
So much nicer and neater! Could you please escape the first decimal point? I tested it with the string "€2B983,-" as an example and it gets detected as a price because the unescaped full-stop means 'any character'.

Other than that, awesome 🎉

2017-05-24 10:19 UTC, tamacodechi commented on .rubocop_todo.yml
> +    - 'spec/detectors/price_detector_spec.rb'
Hmmm, the new Rubocop just came out today, so I don't know if that's it, but how come your autoconfig of rubocop generated so much? I pulled your branch and ran it and it's still only 36 lines long. Can you try running rubocop with `--auto-correct`? A lot of these seem to indicate that auto correct could fix the styling for you 😉

2017-06-09 09:05 UTC, tamacodechi commented on lib/calculations/invoice_number_calculation.rb
> +                     end
👍

2017-06-09 09:05 UTC, tamacodechi commented on .rubocop_todo.yml
> +    - 'spec/detectors/price_detector_spec.rb'
Were you able to find out why the rubocop todo grew so much on this branch? From what I see you haven't done anything to the code base that would cause this many exceptions to be needed.

2017-06-16 10:06 UTC, Tr4in commented on .rubocop_todo.yml
> +    - 'spec/detectors/price_detector_spec.rb'
This happens after running --auto-correct on rubocop and docker-compose run tests rspec

/usr/local/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:402:in `visit_Psych_Nodes_Alias': Unknown alias: default (Psych::BadAlias)
	from /usr/local/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `each'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `each_slice'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:338:in `block in revive_hash'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `each'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `each_slice'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:336:in `revive_hash'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:162:in `visit_Psych_Nodes_Mapping'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:311:in `visit_Psych_Nodes_Document'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/visitor.rb:16:in `visit'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/visitor.rb:6:in `accept'
	from /usr/local/lib/ruby/2.3.0/psych/visitors/to_ruby.rb:32:in `accept'
	from /usr/local/lib/ruby/2.3.0/psych.rb:302:in `safe_load'
	from /myapp/lib/config.rb:11:in `<class:Config>'
	from /myapp/lib/config.rb:6:in `<top (required)>'
	from /myapp/lib/bill_recognizer.rb:45:in `require_relative'
	from /myapp/lib/bill_recognizer.rb:45:in `<top (required)>'
	from /myapp/spec/acceptance/bill_recognition_spec.rb:4:in `require_relative'
	from /myapp/spec/acceptance/bill_recognition_spec.rb:4:in `<top (required)>'
	from /bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /bundle/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /bundle/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /bundle/gems/rspec-core-3.5.4/exe/rspec:4:in `<top (required)>'
	from /usr/local/bundle/bin/rspec:17:in `load'
	from /usr/local/bundle/bin/rspec:17:in `<main>'

Due to rubocop --auto-correct almost every source file has been corrected!

2017-06-19 12:52 UTC, tamacodechi commented on .rubocop_todo.yml
> +    - 'spec/detectors/price_detector_spec.rb'
Hmmm... Well since this is a rubocop version thing I think it would be best to create a new linting issue to fix all the problems/rules that come with the new version. Do you have time to change to an older version for now so the todo list stays as it was?

2017-06-19 13:52 UTC, merged