225 kilogram as price
clemenshelm/chillbill-recognizer pull request #269
Opened 2017-06-02 16:16 UTC by Tr4in

I'm not satisfied with that, because it only works if numbers are followed by kg!

I tried PriceTerm.right_before(<kg-word>) and it detects:
28,80
3,76
4,24
366,00

The first three aren't prices but the last is one! AND 36,80 was not detected!

![selection_015](https://cloud.githubusercontent.com/assets/21169462/26734744/73ddd2d2-47bf-11e7-95a9-81b33675404d.png)

Closes #225

2017-06-28 08:43 UTC, clemenshelm requested changes

2017-06-28 08:43 UTC, clemenshelm commented on lib/models/price_term.rb
> +      text != 'kg'
Könntest du kürzen auf `word.right_after&.text != 'kg'`.

http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/

2017-06-28 08:43 UTC, clemenshelm commented on lib/detectors/price_detector.rb
> +      end
Sollte überflüssig werden, wenn du den neuen Master reinmergest 😄

2017-06-29 15:50 UTC, clemenshelm approved these changes

2017-06-29 15:50 UTC, clemenshelm commented on lib/models/word.rb
> +  end
Bitte entfernen.

2017-08-08 13:28 UTC, tamacodechi approved these changes
This is now mergeable. Any more feedback @clemenshelm ?

2017-08-09 08:54 UTC, merged

2017-08-09 08:54 UTC, clemenshelm commented
Meeeerged! 😄