created iban-detector
clemenshelm/chillbill-recognizer pull request #28
Opened 2016-10-03 14:21 UTC by Tr4in

Added iban detector, closes #22

2016-10-04 14:44 UTC, tamacodechi commented
Will this get merged before Black Bird, and so need to be covered by #23 ? ![confusedparrot](https://cloud.githubusercontent.com/assets/5068494/19078572/e9ad952e-8a50-11e6-9720-f833bd186245.gif)

2016-10-04 14:46 UTC, clemenshelm commented
Yes, would be nice.

2016-10-05 08:40 UTC, tamacodechi requested changes
Looks really good and clean - just a couple of things to tweak! 👍  Can't wait to see this merged!

2016-10-05 08:40 UTC, tamacodechi commented on lib/bill_recognizer.rb
> +    puts Word.map { |word| "text: #{word.text}, left: #{word.left}, right: #{word.right}, top: #{word.top}, bottom: #{word.bottom}" }
- [x]  Could you comment this out again? We don't want it to have it in the running version ;)

2016-10-05 08:40 UTC, tamacodechi commented on lib/detectors/iban_detector.rb
> +    iban_detected = find_iban(HR_IBAN_REGEX)
Could we use one regex that accepts two characters at the beginning and a range of numbers from 18-20, or would this produce too many false positives? It would be good to just have to call find_iban once, right? :)

2016-10-05 08:40 UTC, tamacodechi commented on spec/acceptance/bill_recognition_spec.rb
> +  end
Did all of these tests fail initially? 

We don't usually add acceptance tests unless they fail because they're not providing any new scenarios to test.

2016-10-05 08:40 UTC, tamacodechi commented on spec/models/iban_term_spec.rb
> +  it 'recognizes Austrain IBAN correctly'  do
Tiny typo: Austrian

2016-10-05 08:40 UTC, tamacodechi commented on lib/detectors/iban_detector.rb
> +require 'bigdecimal'
What are we using these for here?
(Genuine question! I haven't needed them myself yet)

2016-10-06 13:08 UTC, Tr4in commented on spec/acceptance/bill_recognition_spec.rb
> +  end
This test does not fail - this means I have to remove it?

2016-10-06 13:11 UTC, tamacodechi commented on spec/acceptance/bill_recognition_spec.rb
> +  end
Well, the whole point is that we create an acceptance test that provides data: 
If the test fails, we write unit test and write/fix our methods. 
If it doesn't fail, the features that make it work have already been tested/written because of another test that is similar - so we don't need it and can remove it 😉

2016-10-06 19:21 UTC, Tr4in commented on lib/detectors/iban_detector.rb
> +    iban_detected = find_iban(HR_IBAN_REGEX)
If I use one universal regex for these three then the recognizer does not recognize DE ibans anymore.

2016-10-06 19:21 UTC, Tr4in commented on lib/detectors/iban_detector.rb
> +require 'bigdecimal'
Deleted! :)

2016-10-11 14:37 UTC, tamacodechi requested changes
Just one teeny tiny thing and then it's perfect 🎉  Great job @Tr4in :)

2016-10-11 14:37 UTC, tamacodechi commented on lib/bill_recognizer.rb
> +    logger.debug Word.map { |word| "text: #{word.text}, left: #{word.left}, right: #{word.right}, top: #{word.top}, bottom: #{word.bottom}" }
Could you comment this out too? We don't need this one in the running version either 😉

2016-10-18 13:58 UTC, tamacodechi commented
@Tr4in could you take a look at this again? The conflicting files are because master has changed in some files that you changed as well. 

Have you dealt with merge conflicts before? You're going to have to merge master onto your branch and make it so that your work is in the new version, while keeping the changes that were done to master.

Here's a nice article on merge conflicts: [boop](https://www.git-tower.com/learn/git/ebook/en/command-line/advanced-topics/merge-conflicts) If you need any help lemme know 😉

2016-10-19 12:59 UTC, clemenshelm requested changes

2016-10-19 12:59 UTC, clemenshelm commented on lib/bill_recognizer.rb
> +      ibanNumber: iban_number
IBAN already stands for _International Bank Account Number_, so `ibanNumber` is kind of redundant 😄 

Please use just `iban`.

2016-10-20 21:51 UTC, Tr4in commented on lib/bill_recognizer.rb
> +      ibanNumber: iban_number
Changed

2016-10-21 15:04 UTC, tamacodechi commented
Please run `rubocop` and see if there are any offenses.  They will probably mostly be lines that are too long in the test data so feel free to look at the others and style it similarly eg.

```
Term.create(
    text: 'sdfsdf',
    left: 21231,
    right: 123123,
    top: 231,
    bottom: 1231231
)
```

You can also run `rubocop -a` to autofix any problems like needing single quotes instead of double quotes.

2016-10-27 09:23 UTC, clemenshelm approved these changes

2016-10-27 11:00 UTC, tamacodechi requested changes
Looks really great! 🎉 

I tried running it on my machine to see if requiring the detector on the calculator was actually necessary and interestingly enough I get an error, can't run the tests on this branch.

It tells me that the running version's bundler is older so I have to update, but when I try to via docker-compose I get `Could not find rake-11.3.0 in any of the sources` . I've only gotten this on this branch, and now that I pulled in the newest changes, because when we worked together on it last week it was fine. I imagine that the version you had pushed did not have the updated Gemfile.lock

I would say go back to the older version on the branch, since we have this version on all branches. That or update the running version 😉  Then you'll be able to run the tests too :D

2016-10-27 11:00 UTC, tamacodechi commented on spec/calculations/iban_calculation_spec.rb
> +    IbanTerm.dataset.delete
This too?

2016-10-27 11:00 UTC, tamacodechi commented on lib/models/iban_term.rb
> +# TODO: unit test
You already wrote unit tests, so I don't think this comment's necessary :)

2016-10-27 11:00 UTC, tamacodechi commented on spec/calculations/iban_calculation_spec.rb
> +require_relative '../../lib/models/iban_term'
Should this be in spec helper along with the others? What do you think? 😁

2016-10-27 11:00 UTC, tamacodechi commented on spec/detectors/iban_detector_spec.rb
> +require_relative '../../lib/models/word'
boot and word are in the spec helper, so you don't need to require them in any spec file 😉  They're loaded up before any tests run

2016-10-27 11:00 UTC, tamacodechi commented on spec/detectors/iban_detector_spec.rb
> +  end
The word dataset is already cleared by spec helper, so you can remove it here :)

2016-10-27 11:00 UTC, tamacodechi commented on spec/models/iban_term_spec.rb
> +require_relative '../../lib/boot'
Already required by the spec helper so you don't need to require it here 😉

2016-10-27 11:00 UTC, tamacodechi commented on lib/bill_recognizer.rb
> +    # image_file.close
Do we need this here before and after the currency calculation runs?

2016-10-27 11:00 UTC, tamacodechi commented on lib/detectors/iban_detector.rb
> +  class << self
This was done to actually make the filter function private, right? It works just as well, but I think we should keep the code base looking kind of uniform so maybe it would be better to declare private within filter? That or change all the other detectors to be like this one.

2016-10-27 13:32 UTC, tamacodechi commented
Awesome, it's great! 😁 
Could you merge in master to your branch? It should then be totally done I think! 👍

2016-10-27 14:12 UTC, merged