267 parse qr codes
clemenshelm/chillbill-recognizer pull request #314
Opened 2017-07-17 12:31 UTC by tamacodechi

Closes #267 

I'm not terribly happy with the way it's implemented in the recognizer but it works 😅 I'd love some input on how to make that a bit nicer...

Also I've kept the uncompacted prices, is that something we would want? 🦄

2017-07-19 08:25 UTC, clemenshelm requested changes
Nice! Looking forward to shipping this 😄

2017-07-19 08:25 UTC, clemenshelm commented on lib/bill_recognizer.rb
> +                end,
I think it would be more readable to write something like

```ruby
# Calculate all things that need to get calculated anyway
attributes = {
 billingPeriod: calculate_billing_period,
  …
}
if @qr_data
  attributes.merge(@qr_data) # @qrdata should contain everything in the right format (especially dates)
else
  attributes.merge(
    amounts: calculate_amounts,
    …
  )
end
```

2017-07-19 08:25 UTC, clemenshelm commented on lib/qr_decoder.rb
> +    all_data = @qr_codes.last.instance_variable_get(:@data).split('_')
You cannot rely on `@qr_codes` being set here. You silently require `qr_code?` to be called first.

Better solution: Make a private method `qr_codes` and use it instead of the instance variables:

```ruby
def qr_code?
  !qr_codes.empty?
end

def decode_qr_code
  return unless qr_code?
  all_data = qr_codes.last.data.split('_')
  …
end

private

def qr_codes
  return @qr_codes if @qr_codes

  tmp_image = @image.dup
  image_blob = tmp_image.to_blob do
    self.depth = 8
    self.format = 'PGM'
  end
  @qr_codes = ZBar::Image.from_pgm(image_blob).process(symbology: :qrcode)
end
```

2017-07-19 08:25 UTC, clemenshelm commented on lib/qr_decoder.rb
> +    all_data = @qr_codes.last.instance_variable_get(:@data).split('_')
Why did you use `.instance_variable_get(:@data)`? Doesn't just `.data` work?

2017-07-19 08:25 UTC, clemenshelm commented on lib/qr_decoder.rb
> +    prices = all_data.find_all { |price| /\d,\d{2}/ =~ price }
```ruby
prices = all_data.grep(/\d,\d{2}/)
```

2017-07-19 08:25 UTC, clemenshelm commented on lib/qr_decoder.rb
> +      dueDate: DateTime.strptime(all_data[4], '%Y-%m-%d'),
This should already be in the right date format (as a string), so we can just merge it into the bill result.

2017-07-19 08:25 UTC, clemenshelm commented on lib/qr_decoder.rb
> +    processed_data
You don't need the `processed_data` variable as the last statement (the result hash) is returned implicitly anyway.

2017-07-19 08:26 UTC, clemenshelm commented on lib/bill_recognizer.rb
> +                end,
The comments are only meant for you and don't have to go into the code 😄

2017-07-19 09:07 UTC, tamacodechi commented on lib/bill_recognizer.rb
> +                end,
Hmm, I thought about this, but does it make sense to go through calculating things that we won't need anyway? Also if something depended on another value, like it often does with the dates, if our recognizer picked up something wrong it would carry over onto the other calculations and then the original value will be correctly overwritten. 

Those were my concerns 😰

2017-07-19 09:08 UTC, tamacodechi commented on lib/qr_decoder.rb
> +    all_data = @qr_codes.last.instance_variable_get(:@data).split('_')
Okay! That sounds good! I did want to make it a private method but I wasn't sure if overcomplicating it by splitting it up would be well received 😅

2017-07-19 09:09 UTC, tamacodechi commented on lib/qr_decoder.rb
> +    processed_data
Whoops, left over from prying 😅  Thank you for pointing it out!! 😂

2017-07-19 09:09 UTC, tamacodechi commented on lib/qr_decoder.rb
> +    prices = all_data.find_all { |price| /\d,\d{2}/ =~ price }
👍

2017-07-19 11:10 UTC, clemenshelm commented on lib/bill_recognizer.rb
> +                end,
This code doesn't go through calculating things that we won't need anyway. All these things are in the `else` branch.

I don't understand the second point entirely. Can you give me an example?

2017-07-19 11:12 UTC, clemenshelm commented on lib/qr_decoder.rb
> +    all_data = @qr_codes.last.instance_variable_get(:@data).split('_')
In general supposing your public methods to be called in a specific order is bad practice as it will break easily.

2017-07-19 11:40 UTC, tamacodechi commented on lib/bill_recognizer.rb
> +                end,
Ahh okay I misunderstood and thought it would be overwriting the already recognized and calculated values 😅 The second point is moot with that clarification too 😂

2017-07-26 11:58 UTC, clemenshelm requested changes
Good job! Just one little remark about formatting.

2017-07-26 11:58 UTC, clemenshelm commented on lib/qr_decoder.rb
> +    }
A bit hard to read this way. Could you put the results into variables first and add them to the hash afterwards? A rule of thumb could be: if it fits into one line, put it into the hash, otherwise into a separate step 🙂

2017-07-26 13:05 UTC, clemenshelm approved these changes
Great work! 🎉

2017-07-26 13:05 UTC, merged