Remove trimming, create text box and rewrite test data now that trimming is removed
clemenshelm/chillbill-recognizer pull request #315
Opened 2017-07-26 06:08 UTC by tamacodechi

Closes #310 
This is just the text box creation, testing and removal of trimming 🦊 ✨ 
I'm rewriting the test data now but I didn't want to clutter the PR with all of that yet.

2017-07-26 07:53 UTC, clemenshelm requested changes
Looking very good so far!

2017-07-26 07:53 UTC, clemenshelm commented on lib/models/bill_dimension.rb
> +      text_box_top:, text_box_bottom:, text_box_left:, text_box_right:
Since the method name already informs about the scope "text_box", I think it's sufficient to name the arguments `top:, bottom:, left:, :right`.

2017-07-26 07:53 UTC, clemenshelm commented on lib/models/bill_dimension.rb
> +      BillDimension.create(name: 'text_box_right', dimension: text_box_right)
Bill dimension names are good the way they are, though. Don't change them 😄

2017-07-26 07:53 UTC, clemenshelm commented on lib/bill_recognizer.rb
> +    text_box_top = Word.select_order_map(:top).first
Where does `Word.select_order_map` come from? It's neither in the pull request nor on master. Either way, you should come up with a more descriptive name of what's the purpose of this method. It does something like determining the maximum boundary of one dimension, right?

2017-07-26 08:07 UTC, tamacodechi commented on lib/bill_recognizer.rb
> +    text_box_top = Word.select_order_map(:top).first
It's a sequel querying method. Should I create a method that just does this in order to make it more legible? Although... within that method the reader might still wonder what the method does 🙈

2017-07-26 08:08 UTC, tamacodechi commented on lib/models/bill_dimension.rb
> +      BillDimension.create(name: 'text_box_right', dimension: text_box_right)
Okay! 😀  So here I should keep them as `text_top` etc.. or just top, bottom, left, right?

2017-07-26 08:09 UTC, tamacodechi commented on lib/models/bill_dimension.rb
> +      text_box_top:, text_box_bottom:, text_box_left:, text_box_right:
Phew, okay! That's better, since it gets a bit long it would be nice to have it shorter as well 😊

2017-08-01 12:22 UTC, clemenshelm reviewed
Just a few questions about naming 🙂

2017-08-01 12:22 UTC, clemenshelm commented on lib/tasks/machine_learning/add_dimensions.rake
> +        'bill_type' => 'A4'
Wouldn't `format` be a nicer name in the context of dimensions?

2017-08-01 12:22 UTC, clemenshelm commented on lib/models/bill_dimension.rb
> +    def text_box_boundaries(top:, bottom:, left:, right:)
Maybe `create_text_boundaries`? Otherwise it's not clear what will happen in this method.

2017-08-01 12:22 UTC, clemenshelm commented on lib/models/bill_dimension.rb
>        BillDimension.create(name: 'bill_height', dimension: height)
In a way it's strange that this method is called `create_all` but doesn't create the text boundaries. Why did you choose to make a separate method?

2017-08-01 12:42 UTC, tamacodechi commented on lib/tasks/machine_learning/add_dimensions.rake
> +        'bill_type' => 'A4'
Sure, just checked with @Thomas1e and that name works for him too ;)

2017-08-01 12:44 UTC, tamacodechi commented on lib/models/bill_dimension.rb
>        BillDimension.create(name: 'bill_height', dimension: height)
By design we use the bill width and height for the words (which comes before finding the text box, as that depends on the found words). Also Rubocop hates us using more that 5 parameters... but I mean we could have them as one 🤷‍♀️

2017-08-01 12:44 UTC, tamacodechi commented on lib/models/bill_dimension.rb
> +    def text_box_boundaries(top:, bottom:, left:, right:)
True 🤔 Will change it right away!

2017-08-01 13:41 UTC, clemenshelm approved these changes

2017-08-01 13:41 UTC, merged