289 weight recognized as price
clemenshelm/chillbill-recognizer pull request #336
Opened 2017-08-10 08:30 UTC by tamacodechi

Closes #289

2017-08-10 08:33 UTC, tamacodechi commented on lib/models/price_term.rb
> +    super && Word.right_after(self)&.text != 'kg' && Word.right_below(self)&.text != 'kg'
Do you know a nicer way to put this rather than `x != z && y != z` ? To kind of say "neither x nor y equals z"
(I want a nor without having to extend the boolean classes 😅 )

2017-08-10 12:06 UTC, clemenshelm commented on lib/models/price_term.rb
> +    super && Word.right_after(self)&.text != 'kg' && Word.right_below(self)&.text != 'kg'
You could write `![Word.right_after(self), Word.right_below(self)].map(&:text).include?('kg')`, but I doubt that this would be more readable 😄

2017-08-10 12:08 UTC, tamacodechi commented on lib/models/price_term.rb
> +    super && Word.right_after(self)&.text != 'kg' && Word.right_below(self)&.text != 'kg'
😂 

Yeah this is why I asked for feedback, the way it is is veeeery clear as to what's happening, but I thought there might be some wonderful ruby magic I might have forgotten

2017-08-10 12:08 UTC, clemenshelm commented on lib/models/price_term.rb
> +    super && Word.right_after(self)&.text != 'kg' && Word.right_below(self)&.text != 'kg'
You could also transform it with de Morgan's rule to `!(Word.right_after(self)&.text == 'kg' || Word.right_below(self)&.text == 'kg')` but yeah … I think it's ok the way it is.

2017-08-10 12:10 UTC, clemenshelm requested changes
Please clarify the conditions.

2017-08-10 12:10 UTC, clemenshelm commented on lib/models/price_term.rb
> +    super && Word.right_after(self)&.text != 'kg' && Word.right_below(self)&.text != 'kg'
How does this actually make the test pass? The "kg" in the example is right above the term, not right below.

2017-08-11 07:43 UTC, tamacodechi commented
🙀 our `right_below` method was so lenient that it would allow things well above to get picked up as well!

Here is the new and shiny `right_above` method 🎉 🎉  I suspect it will soon be too lenient as well but as soon as I apply any limitation (say, the thing above can only be one space above) the test does not pass. Should I limit it with a despotic multiplier which works for this example?

2017-08-11 08:24 UTC, clemenshelm commented on spec/models/dimensionable_spec.rb
> +    end
Spec for right_above is missing.

2017-08-11 08:25 UTC, tamacodechi commented on spec/models/dimensionable_spec.rb
> +    end
Ahh in dimensionable! Oops! 🙊 Thank you!

2017-08-11 08:45 UTC, clemenshelm commented
Have you checked that this solution actually solves the problem of the bill? I'm not so sure about it.

2017-08-11 09:12 UTC, tamacodechi commented
Hmm the tests all pass but I ran it through the recognizer, the problem is that a blank space is detected above it. Spoke to @Tr4in about how the artefact filtering will be designed and it seems it will solve this issue 🎈  Blocked by #332

2017-08-11 09:15 UTC, clemenshelm commented
I don't think it's blocked. The problem is rather that the current `right_above` method will pick up a random word which is located somewhere above on the page, but not necessarily right above the word.

2017-08-11 09:18 UTC, tamacodechi commented
OH! It's picked up the first word to match the criteria which of course is right at the top of the page 🙈 Despotic limiting multiplier it is then 😂

2017-08-16 11:32 UTC, tamacodechi commented
Non despotic multiplier solution, heck yeah! 🙌 
I was going to do the quick fix and refactor it later but I think architecturally this makes more sense, especially since some other issues can reply on `in_the_same_column`

2017-08-16 19:48 UTC, Tr4in reviewed
Perfect :sun_with_face:

2017-08-17 16:03 UTC, clemenshelm commented on lib/models/dimensionable.rb
> +      end
This looks quite complex. Wouldn't this condition suffice? `word1.left < word2.right && word2.left < word1.right` meaning that they are overlapping?

2017-08-17 16:04 UTC, clemenshelm commented on lib/models/dimensionable.rb
> +      end
This would pretty much replicate the logic of `on_same_line` 😄

2017-08-17 16:06 UTC, clemenshelm commented on lib/models/dimensionable.rb
> +      end
You could also use it in `right_below`.

2017-08-18 07:38 UTC, tamacodechi commented on lib/models/dimensionable.rb
> +      end
Wouldn't this also pick up things that are not in the same column? I was having a hard time wording it, so I just did a sketch 😅
![6177988448](https://user-images.githubusercontent.com/5068494/29448862-cc84e162-83f8-11e7-897b-c41ced17d678.jpeg)
But in the example the criteria are still met, but to me `above` is not in the same column at all.

It is a little more complex but I think the way it is now is quite robust and easy to refactor should our needs change. It's a little lengthy, but I also did this in exchange for legibility.

![6177966608](https://user-images.githubusercontent.com/5068494/29448861-cc812522-83f8-11e7-9f11-8752b08ba100.jpeg)

2017-08-18 07:39 UTC, tamacodechi commented on lib/models/dimensionable.rb
> +      end
We totally can! And I will apply it now 😉

2017-08-18 07:46 UTC, clemenshelm commented on lib/models/dimensionable.rb
> +      end
What about this case?

<img width="84" alt="bildschirmfoto 2017-08-18 um 09 46 49" src="https://user-images.githubusercontent.com/141632/29449224-323ee7cc-83fa-11e7-9ee0-967227084b61.png">

2017-08-18 08:08 UTC, tamacodechi commented on lib/models/dimensionable.rb
> +      end
I hadn't encountered an example where this was the case (whereby the definition they are in the same column but completely misaligned). 

Could you send me the bill ID? I'd love to look at the word attributes 🦑 

I feel like in this case it applies, but because it's in a table. I don't think we would want words (eg. in a paragraph) that are aligned like this to be in a column by our definition.

2017-08-18 08:56 UTC, clemenshelm commented on lib/models/dimensionable.rb
> +      end
It was a contrived example. Are all of these conditions you wrote necessary to fulfill the needs of the test data you used? To me this really looks like we're overcomplicating things. But if it's necessary for the data to work, I'm convinced 😄

2017-08-22 08:24 UTC, clemenshelm commented
Very nice! 👍

2017-08-22 08:24 UTC, clemenshelm approved these changes

2017-08-22 08:24 UTC, merged