335 qr codes with different formats
clemenshelm/chillbill-recognizer pull request #343
Opened 2017-08-17 14:05 UTC by tamacodechi

Closes #335 

Something I am unhappy with about this issue is that this shop (all examples came from the same shop), seems to have gotten the format of the data within the qr code wrong because they have placed the 13% vat rate second instead of 10% 🐝

2017-08-17 15:55 UTC, clemenshelm requested changes
Please DRY 🙂

2017-08-17 15:55 UTC, clemenshelm commented on lib/qr_decoder.rb
> +    end
This would make a nice little method of its own:

```ruby
def prices_and_date_parts(qr_code_parts)
  if qr_code_parts[1] == 'R1'
    { prices: qr_code_parts[6..10], date: qr_code_parts[5] }
  else
    { prices: qr_code_parts[5..9], date: qr_code_parts[4] }
  end
end
```

It would resolve all the duplication here.

2017-08-18 07:41 UTC, tamacodechi commented on lib/qr_decoder.rb
> +    end
Looks good, I'll do something like this then ✌️ 

I'm always a little unsure of compartmentalising, but would you recommend erring on the side of doing it and then going back and fixing it if it's unnecessary?

2017-08-18 08:54 UTC, tamacodechi commented on lib/qr_decoder.rb
> +    end
I am not 100% sure making a method of it's own was that great a success... 
- Accessing the data makes the lines considerably longer. 
- Unless I am doing something wrong, the prices have to processed at the same time as they are extracted or they are converted into strings, so this has to be repeated (`.map { |p| BigDecimal.ne....`)

Perhaps moving the date processing outside the conditional flow would be a better step forward? 

Of course I don't mind the method otherwise 🎉 I think it makes the `decode_qr_code` cleaner anyway

2017-08-18 12:12 UTC, clemenshelm commented on lib/qr_decoder.rb
> +    end
The `.map { |p| BigDecimal.new(p.sub(',', '.')) }` could also be outside of the method.

Regarding length: You can destructure the resulting hash by writing
`date, prices, vat_rates = filtered_data.values_at(:date, :prices, :vat_rates)`

2017-08-22 08:13 UTC, clemenshelm approved these changes
Good job! 🥇

2017-08-22 08:13 UTC, clemenshelm commented on lib/qr_decoder.rb
> +    end
Very nice. You can also chain the method calls like

```ruby
vat_rates
  .zip(…)
  .select(…)
  .map(…)
```

This way you don't have to come up with variable names all the time. The only condition is that readibility shouldn't suffer by it. In this case I think it would even improve readability because it would emphasize the "data processing pipeline".

You don't need to change it anymore, though, this is just a suggestion for the future.

2017-08-22 08:14 UTC, merged

2017-08-22 08:19 UTC, tamacodechi commented on lib/qr_decoder.rb
> +    end
Oh that does look considerably better... 🙈 I will keep this in mind and fix it when something else comes around on the QR code decoder