first commit
clemenshelm/chillbill-recognizer pull request #357
Opened 2017-08-23 22:59 UTC by Tr4in

Closes #299 

This will punch #229, #240, #241 and #284 too!

2017-08-24 10:52 UTC, tamacodechi requested changes
Awesome! I think only one tiny thing, but it's perfect 👍

2017-08-24 10:52 UTC, tamacodechi commented on lib/models/price_term.rb
> +    # binding.pry
👀

2017-08-24 10:52 UTC, tamacodechi commented on lib/models/word.rb
> +  UNITS = %w(kg % Stunden SK PA SG ST TO KG M3).freeze
Yay 💖 I love that we're doing it this way :)

2017-08-24 10:52 UTC, tamacodechi commented on spec/detectors/price_detector_spec.rb
> +
👍  
But remember when you label a bill you can also just write:
 `# From <bill-id>.<extension>"`

2017-08-24 10:52 UTC, tamacodechi commented on lib/detectors/price_detector.rb
> +  ALLOWED_PREFIX_REGEX = /(?:^|[^\d,A-Za-z\.-])/
Which spec needs this? 🤔

2017-08-24 11:46 UTC, Tr4in commented on lib/detectors/price_detector.rb
> +  ALLOWED_PREFIX_REGEX = /(?:^|[^\d,A-Za-z\.-])/
I put it there because the spec **does not detect prices in a long weird word** which was not merged AND there was a bill with the same problem

2017-08-29 08:30 UTC, tamacodechi requested changes
Can't wait to merge this 🎉 Just a couple of tiny things 😅

2017-08-29 08:30 UTC, tamacodechi commented on lib/models/price_term.rb
> +  def pass_unit_check
This should probably be called `unit_check` because above we're saying `!pass_unit_check` which literally means "not pass unit check"... which it actually _is_ passing! 😁 Or change `pass_unit_check` to actually make sure that they do not include the unit words.

I actually like the name `pass_unit_check` so I would prefer the second fix, but it's up to how you prefer 😉

2017-08-29 08:30 UTC, tamacodechi commented on spec/detectors/price_detector_spec.rb
> +  it 'does not detect prices' do
I hope it detects price! 🙈  I think you mean it doesn't detect hours as prices, right? :)

2017-08-29 08:30 UTC, tamacodechi commented on spec/detectors/price_detector_spec.rb
> +  it 'does not detect multi units' do
"multiple units as prices"
🙈 🙈 So picky 😂 😂

2017-08-29 11:44 UTC, tamacodechi approved these changes
Ideally the spec where you are testing for multiple units would be broken into individual specs so they can be more descriptive. From that one spec name we can't really know which of the units are being tested against 😉 

👏 👏  Good job! 👍

2017-08-29 11:45 UTC, merged