24 due date recognizer
clemenshelm/chillbill-recognizer pull request #55
Opened 2016-10-25 15:24 UTC by tamacodechi

closes #24

2016-10-27 09:22 UTC, clemenshelm requested changes
Oh yeah! 😄

2016-10-27 09:22 UTC, clemenshelm commented on lib/calculations/due_date_calculation.rb
> +    due_date_label = Word.right_after(due_word.first) if due_word
In what case is `due_word` falsy? It's only a Sequel query, so it should always be defined.

2016-10-27 09:22 UTC, clemenshelm commented on lib/models/dimensionable.rb
> +          ((current.bottom * 0.95) <= following.bottom))
Multiplying `current.bottom` doesn't make a lot of sense: If the word is closer to the bottom of the page, the product will be significatly larger (because the bottom value is a lot larger). I'd use `height` instead as this stays constant on the whole page.

2016-10-27 09:22 UTC, clemenshelm commented on lib/models/dimensionable.rb
> +          ((current.bottom * 0.95) <= following.bottom))
Why have you defined `all.find…` twice? The first one won't have any effect now as the result is just discarded.

2016-10-27 09:22 UTC, clemenshelm commented on lib/models/dimensionable.rb
> +          ((current.bottom * 0.95) <= following.bottom))
Can you please write specs for this method?

2016-10-27 13:19 UTC, tamacodechi commented on lib/calculations/due_date_calculation.rb
> +    due_date_label = Word.right_after(due_word.first) if due_word
Whoops! My bad! I intended it for if due_word was empty so it wouldn't run .right_after on nil. Added a test for this (because the one that returns nil is when there are no words contained, not "no due dates") and fixed 👍

2016-10-27 16:56 UTC, tamacodechi commented on lib/models/dimensionable.rb
> +          ((current.bottom * 0.95) <= following.bottom))
Please let me know if this makes sense 😅  

The reason I'm going through `all.find` twice is because I need to iterate over the words twice:
Once to find if there are any words on the same line, and if there are none, then another time to find if there are any words slightly above or below. 

I can't do this as a nested loop or condition because then _it will just take whichever term came first_. I don't want this because we explicitly need to see if there are any terms on the same line first, and then _if there are none_ find ones slightly below or above.

Is there another way I can solve this? This is why I had originally built a `on_same_line` method.

2016-11-02 10:36 UTC, clemenshelm approved these changes

2016-11-02 10:36 UTC, merged