31 wrong american date
clemenshelm/chillbill-recognizer pull request #58
Opened 2016-11-03 13:16 UTC by Tr4in

Hopefully fixed the problem with the American date. Closes #31

2016-11-03 13:40 UTC, clemenshelm requested changes
Nice! Ein paar kleine Änderungen, bitte 😄

2016-11-03 13:40 UTC, clemenshelm commented on spec/acceptance/bill_recognition_spec.rb
> +    # There is no IBAN number
Da hätte ich eigentlich gemeint, dass du die wieder löscht, die du selbst geschrieben hast. Also immer die alte drinnen lassen ;)

2016-11-03 13:40 UTC, clemenshelm commented on spec/calculations/date_calculation_spec.rb
> +    expect(date_calculation.invoice_date).to eq DateTime.iso8601('2016-08-13')
Hier weiß man aber nicht, ob er jetzt das erste oder das zweite Datum genommen hat. Kannst du den zweiten `DateTerm`entfernen?

2016-11-03 13:40 UTC, clemenshelm commented on spec/models/date_term_spec.rb
> +    term = DateTerm.new(text: '12/03/16')
Wieso hast du das geändert? Jetzt ist der Fall nicht mehr getestet, wenn der Tag nur aus einer Stelle besteht.

2016-11-03 13:40 UTC, clemenshelm commented on spec/detectors/date_detector_spec.rb
> +    expect(date_strings(dates)).to eq word_order
Was ist der Vorteil daran, das hinzuzufügen?

2016-11-03 17:02 UTC, Tr4in commented on spec/detectors/date_detector_spec.rb
> +    expect(date_strings(dates)).to eq word_order
Laut rubocop überschreitet die alte Syntax die Linie

2016-11-04 09:06 UTC, clemenshelm approved these changes

2016-11-04 09:06 UTC, merged