Make vat ID detector return an empty data set if there are no words
clemenshelm/chillbill-recognizer pull request #80
Opened 2016-11-11 12:33 UTC by tamacodechi

closes #75

2016-11-11 14:12 UTC, clemenshelm requested changes

2016-11-11 14:12 UTC, clemenshelm commented on lib/bill_recognizer.rb
> +
No whitespace, please 😄

2016-11-11 14:12 UTC, clemenshelm commented on lib/bill_recognizer.rb
> +
Doesn't Rubocop lint this?

2016-11-11 14:15 UTC, tamacodechi commented on lib/bill_recognizer.rb
> +
Strange thing is that it allowed it and it wouldn't pass the CI tests if it didn't. I also spotted this when I was creating the PR but I thought it was harmless since Rubocop didn't mind. I can remove it 😉

2016-11-16 14:24 UTC, clemenshelm approved these changes

2016-11-16 14:24 UTC, merged